train: /home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/region_performace/punjab_same_class_count_10_120_1000
val: /home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/region_performace/test_bihar_same_class_count_10_120_1000
names: ['CFCBK','FCBK', 'Zigzag']
