train: /home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/swinir_data/m0_obb_without_empty_train_4x
val: /home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/swinir_data/m0_obb_without_empty_val_4x
nc: 3
names: ['CFCBK','FCBK', 'Zigzag']
