train: /home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/region_performace/punjab_same_class_count
val: /home/rishabh.mondal/Brick-Kilns-project/ijcai_2025_kilns/data/region_performace/test_bihar_same_class_count
names: ['CFCBK','FCBK', 'Zigzag']
